/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.MarcaControle;
import controle.ModeloControle;
import controle.ProprietarioControle;
import controle.RegistraGastoControle;
import controle.VeiculoControle;
import java.util.ArrayList;
import modelos.IMarcaCRUD;
import modelos.IModeloVeiculo;
import modelos.IVeiculoCRUD;
import modelos.IPropietarioCRUD;
import modelos.IRegistraGastosCRUD;
import modelos.RegistraGastos;


public class TelaPrincipal extends javax.swing.JFrame {

    IPropietarioCRUD cadastroProprietarioControle = null;


    public TelaPrincipal() {
        initComponents();
        this.setTitle("SCGV - Sistema de Controle de Gastos Veicular");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        cadastroProprietarioControle = new ProprietarioControle();
        totalMarcas();
        totalModelos();
        totalVeiculos();
        totalProprietario();
        totalDeGastos();
    }

    private void totalMarcas() {
        try {
            int marcasCount = 0;
            IMarcaCRUD marcas = null;
            marcas = new MarcaControle();
            marcasCount = marcas.listagemDeMarcas().size();
            jLabel_MarcasCount.setText(marcasCount + "");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    private void totalModelos() {
        try {
            int modelosCount = 0;
            IModeloVeiculo modelo = null;
            modelo = new ModeloControle();
            modelosCount = modelo.listagemDeModelos().size();
            jLabel_ModelosCount.setText(modelosCount + "");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    private void totalVeiculos() {
        try {
            int veiculoCount = 0;
            IVeiculoCRUD veiculo = null;
            veiculo = new VeiculoControle();
            veiculoCount = veiculo.listagemDeVeiculos().size();
            jLabel_VeiculoCount.setText(veiculoCount + "");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    private void totalProprietario() {
        try {
            int proprietarioCount = 0;
            IPropietarioCRUD proprietario = null;
            proprietario = new ProprietarioControle();
            proprietarioCount = proprietario.listagemDePropietario().size();
            jLabel_ProprietarioCount.setText(proprietarioCount + "");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    private void totalDeGastos() {
        try {
            float valorGasto = 0;
            IRegistraGastosCRUD gastosControle = null;
            gastosControle = new RegistraGastoControle();

            ArrayList<RegistraGastos> listaDeGastos = null;
            listaDeGastos = gastosControle.listagemRegistroDeGastos();
            if (listaDeGastos.isEmpty()) {
                return;
            }
            for (RegistraGastos i : listaDeGastos) {
                valorGasto += i.getValorGasto();
            }
            jLabel_TotalGastos.setText("R$" + valorGasto + "");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Marcas = new javax.swing.JPanel();
        jLabel_MarcasCount = new javax.swing.JLabel();
        jPanel_Modelos = new javax.swing.JPanel();
        jLabel_ModelosCount = new javax.swing.JLabel();
        jPanel_Veiculos = new javax.swing.JPanel();
        jLabel_VeiculoCount = new javax.swing.JLabel();
        jPanel_Proprietarios = new javax.swing.JPanel();
        jLabel_ProprietarioCount = new javax.swing.JLabel();
        jPanel_Marcas4 = new javax.swing.JPanel();
        jLabel_TotalGastos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Cadastro = new javax.swing.JMenu();
        jMenuItem_MarcaVeiculo = new javax.swing.JMenuItem();
        jMenuItem_ModeloVeiculo = new javax.swing.JMenuItem();
        jMenuItem_Veículo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Proprietário = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_TipoDeGasto = new javax.swing.JMenuItem();
        jMenu_Consultar = new javax.swing.JMenu();
        jMenuItem_ConsultarProprietario = new javax.swing.JMenuItem();
        jMenu_ConsultarVeiculo = new javax.swing.JMenuItem();
        jMenu_Relatorio = new javax.swing.JMenu();
        jMenuItem_GerarRelatorio = new javax.swing.JMenuItem();
        jMenu_About = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SCGV1/SCGV1.gif"))); // NOI18N

        jPanel_Marcas.setBackground(new java.awt.Color(0, 204, 255));
        jPanel_Marcas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel_Marcas.setMaximumSize(new java.awt.Dimension(134, 91));
        jPanel_Marcas.setMinimumSize(new java.awt.Dimension(134, 91));

        jLabel_MarcasCount.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel_MarcasCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MarcasCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MarcasCount.setText("000");

        javax.swing.GroupLayout jPanel_MarcasLayout = new javax.swing.GroupLayout(jPanel_Marcas);
        jPanel_Marcas.setLayout(jPanel_MarcasLayout);
        jPanel_MarcasLayout.setHorizontalGroup(
            jPanel_MarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_MarcasCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MarcasLayout.setVerticalGroup(
            jPanel_MarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MarcasLayout.createSequentialGroup()
                .addComponent(jLabel_MarcasCount)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Modelos.setBackground(new java.awt.Color(0, 204, 255));
        jPanel_Modelos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modelos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel_Modelos.setMaximumSize(new java.awt.Dimension(134, 91));
        jPanel_Modelos.setMinimumSize(new java.awt.Dimension(134, 91));

        jLabel_ModelosCount.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel_ModelosCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModelosCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ModelosCount.setText("000");

        javax.swing.GroupLayout jPanel_ModelosLayout = new javax.swing.GroupLayout(jPanel_Modelos);
        jPanel_Modelos.setLayout(jPanel_ModelosLayout);
        jPanel_ModelosLayout.setHorizontalGroup(
            jPanel_ModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ModelosCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ModelosLayout.setVerticalGroup(
            jPanel_ModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ModelosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_ModelosCount))
        );

        jPanel_Veiculos.setBackground(new java.awt.Color(0, 204, 255));
        jPanel_Veiculos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel_Veiculos.setMaximumSize(new java.awt.Dimension(134, 91));
        jPanel_Veiculos.setMinimumSize(new java.awt.Dimension(134, 91));

        jLabel_VeiculoCount.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel_VeiculoCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_VeiculoCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_VeiculoCount.setText("000");

        javax.swing.GroupLayout jPanel_VeiculosLayout = new javax.swing.GroupLayout(jPanel_Veiculos);
        jPanel_Veiculos.setLayout(jPanel_VeiculosLayout);
        jPanel_VeiculosLayout.setHorizontalGroup(
            jPanel_VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VeiculosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_VeiculoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_VeiculosLayout.setVerticalGroup(
            jPanel_VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VeiculosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_VeiculoCount))
        );

        jPanel_Proprietarios.setBackground(new java.awt.Color(0, 204, 255));
        jPanel_Proprietarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proprietários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel_Proprietarios.setMaximumSize(new java.awt.Dimension(134, 91));
        jPanel_Proprietarios.setMinimumSize(new java.awt.Dimension(134, 91));

        jLabel_ProprietarioCount.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel_ProprietarioCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ProprietarioCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ProprietarioCount.setText("000");

        javax.swing.GroupLayout jPanel_ProprietariosLayout = new javax.swing.GroupLayout(jPanel_Proprietarios);
        jPanel_Proprietarios.setLayout(jPanel_ProprietariosLayout);
        jPanel_ProprietariosLayout.setHorizontalGroup(
            jPanel_ProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ProprietarioCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ProprietariosLayout.setVerticalGroup(
            jPanel_ProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProprietariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_ProprietarioCount))
        );

        jPanel_Marcas4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel_Marcas4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Gastos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel_Marcas4.setMaximumSize(new java.awt.Dimension(134, 91));
        jPanel_Marcas4.setMinimumSize(new java.awt.Dimension(134, 91));

        jLabel_TotalGastos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel_TotalGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TotalGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TotalGastos.setText("000");

        javax.swing.GroupLayout jPanel_Marcas4Layout = new javax.swing.GroupLayout(jPanel_Marcas4);
        jPanel_Marcas4.setLayout(jPanel_Marcas4Layout);
        jPanel_Marcas4Layout.setHorizontalGroup(
            jPanel_Marcas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_TotalGastos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        jPanel_Marcas4Layout.setVerticalGroup(
            jPanel_Marcas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Marcas4Layout.createSequentialGroup()
                .addComponent(jLabel_TotalGastos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Marcas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel_Marcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel_Modelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel_Veiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel_Proprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Marcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Modelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Veiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Proprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Marcas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        jMenu_Cadastro.setMnemonic('c');
        jMenu_Cadastro.setText("Cadastro");

        jMenuItem_MarcaVeiculo.setMnemonic('m');
        jMenuItem_MarcaVeiculo.setText("Marca veículo");
        jMenuItem_MarcaVeiculo.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem_MarcaVeiculoMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItem_MarcaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MarcaVeiculoActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_MarcaVeiculo);

        jMenuItem_ModeloVeiculo.setMnemonic('o');
        jMenuItem_ModeloVeiculo.setText("Modelo veículo");
        jMenuItem_ModeloVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ModeloVeiculoActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_ModeloVeiculo);

        jMenuItem_Veículo.setMnemonic('v');
        jMenuItem_Veículo.setText("Veículo");
        jMenuItem_Veículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_VeículoActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_Veículo);
        jMenu_Cadastro.add(jSeparator1);

        jMenuItem_Proprietário.setMnemonic('p');
        jMenuItem_Proprietário.setText("Proprietário");
        jMenuItem_Proprietário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ProprietárioActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_Proprietário);
        jMenu_Cadastro.add(jSeparator2);

        jMenuItem_TipoDeGasto.setMnemonic('r');
        jMenuItem_TipoDeGasto.setText("Registrar Gastos");
        jMenuItem_TipoDeGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TipoDeGastoActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_TipoDeGasto);

        jMenuBar1.add(jMenu_Cadastro);

        jMenu_Consultar.setMnemonic('o');
        jMenu_Consultar.setText("Consultar");

        jMenuItem_ConsultarProprietario.setMnemonic('p');
        jMenuItem_ConsultarProprietario.setText("Proprietário");
        jMenuItem_ConsultarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarProprietarioActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenuItem_ConsultarProprietario);

        jMenu_ConsultarVeiculo.setMnemonic('v');
        jMenu_ConsultarVeiculo.setText("Veículo");
        jMenu_ConsultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ConsultarVeiculoActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenu_ConsultarVeiculo);

        jMenuBar1.add(jMenu_Consultar);

        jMenu_Relatorio.setMnemonic('e');
        jMenu_Relatorio.setText("Relatório");

        jMenuItem_GerarRelatorio.setMnemonic('g');
        jMenuItem_GerarRelatorio.setText("Gerar relatório");
        jMenuItem_GerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GerarRelatorioActionPerformed(evt);
            }
        });
        jMenu_Relatorio.add(jMenuItem_GerarRelatorio);

        jMenuBar1.add(jMenu_Relatorio);

        jMenu_About.setMnemonic('s');
        jMenu_About.setText("Sobre");

        jMenuItem3.setMnemonic('s');
        jMenuItem3.setText("Sobre o SCGV");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_About.add(jMenuItem3);

        jMenuBar1.add(jMenu_About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_MarcaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MarcaVeiculoActionPerformed
        TelaCadastroMarca cadastroMarca = new TelaCadastroMarca();
        cadastroMarca.dispose();
        cadastroMarca.setLocationRelativeTo(this);
        cadastroMarca.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroMarca.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_MarcaVeiculoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaSobreSCGV sobreSCGV = new TelaSobreSCGV();
        sobreSCGV.dispose();
        sobreSCGV.setLocationRelativeTo(this);
        sobreSCGV.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sobreSCGV.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem_ModeloVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ModeloVeiculoActionPerformed
        TelaCadastroModelo cadastroModelo = new TelaCadastroModelo();
        cadastroModelo.dispose();
        cadastroModelo.setLocationRelativeTo(this);
        cadastroModelo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroModelo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_ModeloVeiculoActionPerformed

    private void jMenuItem_TipoDeGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TipoDeGastoActionPerformed
        TelaRegistroGastos registroGastos = new TelaRegistroGastos();
        registroGastos.dispose();
        registroGastos.setLocationRelativeTo(this);
        registroGastos.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        registroGastos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_TipoDeGastoActionPerformed

    private void jMenuItem_MarcaVeiculoMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem_MarcaVeiculoMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_MarcaVeiculoMenuKeyPressed

    private void jMenuItem_ProprietárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ProprietárioActionPerformed
        TelaCadastroProprietario cadastroProprietario = new TelaCadastroProprietario();
        cadastroProprietario.dispose();
        cadastroProprietario.setLocationRelativeTo(this);
        cadastroProprietario.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroProprietario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_ProprietárioActionPerformed

    private void jMenuItem_VeículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_VeículoActionPerformed
        TelaCadastroVeiculo cadastroVeiculo = new TelaCadastroVeiculo();
        cadastroVeiculo.dispose();
        cadastroVeiculo.setLocationRelativeTo(this);
        cadastroVeiculo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroVeiculo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_VeículoActionPerformed

    private void jMenu_ConsultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ConsultarVeiculoActionPerformed
        TelaConsultarVeiculo consultarVeiculo = new TelaConsultarVeiculo();
        consultarVeiculo.dispose();
        consultarVeiculo.setLocationRelativeTo(this);
        consultarVeiculo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        consultarVeiculo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_ConsultarVeiculoActionPerformed

    private void jMenuItem_ConsultarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarProprietarioActionPerformed
        TelaConsultarProprietario consultarProprietario = new TelaConsultarProprietario();
        consultarProprietario.dispose();
        consultarProprietario.setLocationRelativeTo(this);
        consultarProprietario.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        consultarProprietario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_ConsultarProprietarioActionPerformed

    private void jMenuItem_GerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GerarRelatorioActionPerformed
        TelaRelatorioGastos relatorioGastos = new TelaRelatorioGastos();
        relatorioGastos.dispose();
        relatorioGastos.setLocationRelativeTo(this);
        relatorioGastos.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        relatorioGastos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_GerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_MarcasCount;
    private javax.swing.JLabel jLabel_ModelosCount;
    private javax.swing.JLabel jLabel_ProprietarioCount;
    private javax.swing.JLabel jLabel_TotalGastos;
    private javax.swing.JLabel jLabel_VeiculoCount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_ConsultarProprietario;
    private javax.swing.JMenuItem jMenuItem_GerarRelatorio;
    private javax.swing.JMenuItem jMenuItem_MarcaVeiculo;
    private javax.swing.JMenuItem jMenuItem_ModeloVeiculo;
    private javax.swing.JMenuItem jMenuItem_Proprietário;
    private javax.swing.JMenuItem jMenuItem_TipoDeGasto;
    private javax.swing.JMenuItem jMenuItem_Veículo;
    private javax.swing.JMenu jMenu_About;
    private javax.swing.JMenu jMenu_Cadastro;
    private javax.swing.JMenu jMenu_Consultar;
    private javax.swing.JMenuItem jMenu_ConsultarVeiculo;
    private javax.swing.JMenu jMenu_Relatorio;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Marcas;
    private javax.swing.JPanel jPanel_Marcas4;
    private javax.swing.JPanel jPanel_Modelos;
    private javax.swing.JPanel jPanel_Proprietarios;
    private javax.swing.JPanel jPanel_Veiculos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
